#!/bin/bash

### Theme
export RED=0xFFfe8067
export ORANGE=0xFFffa04d
export YELLOW=0xFFfff266
export GREEN=0xFF6afba4
export CYAN=0xFF6afbfb
export WHITE=0xFFfff9f5

export TRANSPARENT=0x00000000

export HIGHLIGHT=$ORANGE
export HIGHLIGHT_BORDER=0xFFe88630

export BATTERY_1=0xffa6da95
export BATTERY_2=0xffeed49f
export BATTERY_3=0xfff5a97f
export BATTERY_4=0xffee99a0
export BATTERY_5=0xffed8796

export BLUR=20

# General bar colors
export COLOR_BAR_FILL=0x44140a00
export COLOR_BAR_BORDER=0x22ffffff
export NUMBER_BAR_HEIGHT=36 # 2 * NUMBER_BAR_SPACING + 26 (Item height)
export NUMBER_BAR_BORDER_WIDTH=2
export NUMBER_BAR_SPACING=6
export NUMBER_BAR_PADDING=6
export NUMBER_BAR_CORNER_RADIUS=0

export COLOR_ITEM_NORMAL_ICON=0x66ffffff
export COLOR_ITEM_NORMAL_TEXT=0xCCffffff
export COLOR_ITEM_NORMAL_FILL=0x44140a00
export COLOR_ITEM_NORMAL_BORDER=0x22ffffff
export COLOR_SPACE_FILL=$TRANSPARENT
export NUMBER_ITEM_NORMAL_BORDER_WIDTH=2
export NUMBER_ITEM_SPACE_VERTICAL=0
export NUMBER_ITEM_SPACE_INLINE=8
export NUMBER_ITEM_CORNER_RADIUS=16
export NUMBER_ITEM_HEIGHT=26 # 2 * NUMBER_ITEM_SPACE_VERTICAL + 14 (Font size)

export COLOR_ITEM_ACTIVE_ICON=0xFF663300
export COLOR_ITEM_ACTIVE_TEXT=0xFF663300
export COLOR_ITEM_ACTIVE_FILL=$HIGHLIGHT
export COLOR_ITEM_ACTIVE_BORDER=$HIGHLIGHT_BORDER

export POPUP_BACKGROUND_COLOR=$COLOR_BAR_FILL
export POPUP_BORDER_COLOR=$WHITE
export SHADOW_COLOR=$BLACK

