# window management
cask "nikitabobko/tap/aerospace"
tap "FelixKratz/formulae"
brew "sketchybar"
brew "borders"
cask "font-hack-nerd-font"
cask "sf-symbols"

# shell
cask "ghostty"
brew "fzf"
brew "zoxide"
brew "zsh"
brew "ripgrep"

# languages
brew "go"
brew "node"
brew "pkl"

# other
cask "raycast"
brew "bruno"
